### ISSUE TITLE
Cookies aren't returned by HTTParty

### ISSUE THREAD

**Issue by besi** [jnunemaker/httparty#411]
## The situation

I need to read cookie data from my server, but HTTParty fails to return me the desired `Set-Cookie` headers.
## Testing it

I am using http://httpbin.org/cookies/set?mycookie=fun the following example to test the cookies:
### Request

``` HTTP
GET /cookies/set?mycookie=fun HTTP/1.1
Host: httpbin.org
User-Agent: RESTOnIt/1.2
Connection: close
Accept-Encoding: gzip
Content-Type: text/plain;charset=UTF-8
```
### Response

Please note the `Set-Cookie` header.

``` HTTP
HTTP/1.1 302 FOUND
Server: nginx
Date: Fri, 12 Jun 2015 09:25:49 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 223
Connection: close
Location: /cookies
Set-Cookie: mycookie=fun; Path=/
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

Some Body
```
### Ruby script

This **fails** to display any cookies.

``` ruby
require 'httparty'

url = 'http://httpbin.org/cookies/set?mycookie=fun'
r = HTTParty.get(url)
puts r.headers.to_yaml
```

Result

``` yaml
--- !ruby/object:HTTParty::Response::Headers
header:
  server:
  - nginx
  date:
  - Fri, 12 Jun 2015 09:33:51 GMT
  content-type:
  - application/json
  content-length:
  - '45'
  connection:
  - close
  access-control-allow-origin:
  - '*'
  access-control-allow-credentials:
  - 'true'

```
