### ISSUE TITLE
httparty trying to json parse string w/ invalid byte sequence

### ISSUE THREAD

**Issue by jaypatrickhoward** [jnunemaker/httparty#541]
Previously we were experiencing the issue in #533, so I had us pinned to 0.14.0.  Since that was fixed, I removed the pin and tested with 0.15.5.  Now I'm getting:

Exception Backtrace:  822: unexpected token at '^_�^H'

/usr/local/rvm/gems/ruby-2.2.4/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
/usr/local/rvm/gems/ruby-2.2.4/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.15.5/lib/httparty/parser.rb:123:in `json'
/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.15.5/lib/httparty/parser.rb:143:in `parse_supported_format'
/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.15.5/lib/httparty/parser.rb:108:in `parse'
/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.15.5/lib/httparty/parser.rb:67:in `call'
/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.15.5/lib/httparty/request.rb:383:in `parse_response'
/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.15.5/lib/httparty/request.rb:351:in `block in handle_response'
/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.15.5/lib/httparty/response.rb:25:in `call'
/usr/local/rvm/gems/ruby-2.2.4/gems/httparty-0.15.5/lib/httparty/response.rb:25:in `parsed_response'

When I revert to 0.14.0 this same call works.  I'll try to dig up the raw response we get, but it will take some work.

**Comment by jnunemaker** [comment]
Any more info you can provide would be helpful. Without some idea of the raw response I'm not sure how to fix it.

**Comment by jaypatrickhoward** [comment]
It may have been fixed with the fixes for #542 and #543.  Will test again with latest and report back.

**Comment by jaypatrickhoward** [comment]
Or, since 0.15.5 is still latest, I'll wait for the next release and test with that.

**Comment by jnunemaker** [comment]
0.15.6 is out. Please try and let me know.

**Comment by deep-spaced** [comment]
Unfortunately, I'm seeing this issue on 0.15.6. I'm not able to figure out the exact piece of data causing issues, but here's a partial stack trace in case that might help. 

```
822: unexpected token at '\u001F\x8B\b'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155:in  `parse'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/json-1.8.6/lib/json/common.rb:155:in  `parse'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/httparty-0.15.6/lib/httparty/parser.rb:123:in  `json'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/httparty-0.15.6/lib/httparty/parser.rb:143:in  `parse_supported_format'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/httparty-0.15.6/lib/httparty/parser.rb:108:in  `parse'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/httparty-0.15.6/lib/httparty/parser.rb:67:in  `call'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/httparty-0.15.6/lib/httparty/request.rb:382:in  `parse_response'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/httparty-0.15.6/lib/httparty/request.rb:350:in  `block in handle_response'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/httparty-0.15.6/lib/httparty/response.rb:25:in  `call'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/httparty-0.15.6/lib/httparty/response.rb:25:in  `parsed_response'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/httparty-0.15.6/lib/httparty/response.rb:88:in  `method_missing'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/hashie-3.5.5/lib/hashie/mash.rb:210:in  `deep_update'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/hashie-3.5.5/lib/hashie/mash.rb:124:in  `initialize'
/Users/andrew/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/createsend-4.1.1/lib/createsend/subscriber.rb:63
```

Here's a VCR recording of this type of interaction: 

```
- request:
    method: post
    uri: https://xxx:x@api.createsend.com/api/v3.1/subscribers/000/import.json
    body:
      encoding: UTF-8
      string: '{"Subscribers":[{"Name":"Andrew Greene ","EmailAddress":"mk@mailinator.com","CustomFields":[{"Key":"CMPERSONID","Value":"00000"}]},
      {"Name":"David White ","EmailAddress":"whiteblarghhur@dbtestcolorado.edu","CustomFields":[{"Key":"CMPERSONID","Value":"00001"}]},
      {"Name":"Melissa White ","EmailAddress":"someemail@_d_address.com","CustomFields":[{"Key":"CMPERSONID","Value":"00002"}]}],
      "Resubscribe":false,"QueueSubscriptionBasedAutoresponders":false,"RestartSubscriptionBasedAutoresponders":false}'
    headers:
      User-Agent:
      - createsend-ruby-4.0.1-2.1.2-p95-x86_64-darwin13.0
      Content-Type:
      - application/json; charset=utf-8
      Accept-Encoding:
      - gzip, deflate
  response:
    status:
      code: 201
      message: Created
    headers:
      Server:
      - csw
      Cache-Control:
      - private, s-maxage=0
      Content-Type:
      - application/json; charset=utf-8
      P3p:
      - CP="OTI DSP COR CUR IVD CONi OTPi OUR IND UNI STA PRE"
      Date:
      - Wed, 10 Sep 2014 01:46:10 GMT
      Content-Length:
      - '138'
    body:
      encoding: UTF-8
      string: '{"TotalUniqueEmailsSubmitted":3,"TotalExistingSubscribers":0,"TotalNewSubscribers":3,"DuplicateEmailsInSubmission":[],"FailureDetails":[]}'
    http_version: 
```

Thank you for your work on httparty!
